name = "mustafa-music-api"
main = "src/index.ts"
compatibility_date = "2026-08-27"
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 0.1

[[d1_databases]]
binding = "ANALYTICS_DB"
