"use client";

import "./scene7.css";
import gsap from "gsap";
import { MuCaption, MuHeading, type SceneCtx } from "../sceneKit";

const SONGS = [[31,67],[43,41],[53,57],[64,34],[73,55],[77,72],[57,76],[38,79],[84,42],[67,82]] as const;

export function Scene7() {
  return <section className="mu-scene mu-s7" data-scene="7" aria-label="A two-hop search uses nearby songs to improve the result"><div className="mu-stage mu-s7-stage"><MuHeading className="mu-s7-h">Then we searched in two hops.</MuHeading><div className="mu-s7-board" aria-hidden="true"><svg viewBox="0 0 1040 470" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round"><path className="mu-draw mu-s7-axis" strokeWidth="2" d="M66 405 Q420 398 960 405 M66 405 Q58 250 66 48" /><circle className="mu-s7-query" cx="138" cy="294" r="9" /><path className="mu-draw mu-s7-hop mu-s7-hop--one" strokeWidth="2.5" d="M145 288 Q320 174 450 230" /><path className="mu-draw mu-s7-head mu-s7-head--one" strokeWidth="2.5" d="M450 230 L435 222 M450 230 L437 240" /><path className="mu-draw mu-s7-hop mu-s7-hop--two" strokeWidth="2.5" d="M500 235 Q681 180 814 250" /><path className="mu-draw mu-s7-head mu-s7-head--two" strokeWidth="2.5" d="M814 250 L800 241 M814 250 L799 260" /><circle className="mu-s7-center" cx="486" cy="236" r="9" /><circle className="mu-s7-result" cx="818" cy="252" r="12" /></svg>{SONGS.map(([left,top],i)=><i key={i} className={`mu-s7-song ${i < 4 ? "mu-s7-anchor" : ""}`} style={{left:`${left}%`,top:`${top}%`}}/>)}<span className="mu-s7-step mu-s7-step--one lv-mono">1. find nearby songs</span><span className="mu-s7-step mu-s7-step--two lv-mono">2. search again from their center</span></div><MuCaption className="mu-s7-cap">The first search finds a small group of nearby songs. We average that group into one new position, then search again from there. The second search starts inside the song map, where the songs are already arranged well.</MuCaption></div></section>;
}

export function buildScene7(ctx: SceneCtx): void { if(!ctx.desktop){[".mu-s7-h",".mu-s7-board",".mu-s7-cap"].forEach((selector)=>{const el=ctx.q(selector)[0];if(el)gsap.from(el,{opacity:0,y:28,ease:"none",scrollTrigger:{trigger:el,start:"top 80%",end:"top 38%",scrub:.8}})});return;} const tl=gsap.timeline({scrollTrigger:{trigger:ctx.root,start:"top top",end:"+=400%",pin:true,scrub:1,anticipatePin:1,fastScrollEnd:true}});tl.from(ctx.q(".mu-s7-h"),{opacity:0,y:34,duration:.3},0).fromTo(ctx.q(".mu-s7-axis"),ctx.drawFrom(),{strokeDashoffset:0,duration:.32,ease:"none"},.28).from(ctx.q(".mu-s7-song"),{opacity:0,scale:0,duration:.14,stagger:.04,ease:"none"},.62).from(ctx.q(".mu-s7-cap"),{opacity:0,y:20,duration:.3},1.0).fromTo(ctx.q(".mu-s7-hop--one"),ctx.drawFrom(),{strokeDashoffset:0,duration:.38,ease:"none"},1.2).fromTo(ctx.q(".mu-s7-head--one"),ctx.drawFrom(),{strokeDashoffset:0,duration:.1,ease:"none"},1.55).from(ctx.q(".mu-s7-anchor"),{scale:1.7,duration:.18,stagger:.04,ease:"none"},1.65).fromTo(ctx.q(".mu-s7-center"),{opacity:0,scale:0},{opacity:1,scale:1,duration:.2,ease:"none"},2.0).fromTo(ctx.q(".mu-s7-hop--two"),ctx.drawFrom(),{strokeDashoffset:0,duration:.38,ease:"none"},2.26).fromTo(ctx.q(".mu-s7-head--two"),ctx.drawFrom(),{strokeDashoffset:0,duration:.1,ease:"none"},2.61).fromTo(ctx.q(".mu-s7-result"),{opacity:0,scale:0},{opacity:1,scale:1,duration:.2,ease:"none"},2.72).from(ctx.q(".mu-s7-step"),{opacity:0,duration:.16,stagger:.35},1.28); }
